"""Cross-stack config: portability rules, diffing, and the settings store.

The compatibility test is the one that matters. Copying a Sonarr quality profile into
Radarr writes a profile referencing quality IDs that mean something else there — the
result is corrupt, and nothing downstream would flag it.
"""

from __future__ import annotations

import httpx
import pytest
import respx
from sqlmodel import Session

from mastarr import config_sync, settings_store
from mastarr.config_sync import Action, Portability
from mastarr.db import get_engine
from mastarr.models import Service
from mastarr.services import store_api_key

SONARR_URL = "http://sonarr.test:8989"
RADARR_URL = "http://radarr.test:7878"

SONARR_CF = {
    "id": 1,
    "name": "novoiceover",
    "includeCustomFormatWhenRenaming": False,
    "specifications": [
        {
            "id": 9,
            "name": "no voice over",
            "implementation": "ReleaseTitleSpecification",
            # Service-branded and regenerated by the target — must not affect the diff.
            "implementationName": "Release Title",
            "infoLink": "https://wiki.servarr.com/sonarr/settings#custom-formats-2",
            "negate": False,
            "required": False,
            "fields": [
                {
                    "order": 0,
                    "name": "value",
                    "label": "Regular Expression",
                    "helpText": "Custom Format RegEx is Case Insensitive",
                    "value": "\\b(AD|DVS|VO)\\b",
                    "type": "textbox",
                    "advanced": False,
                }
            ],
        }
    ],
}

# The same format as Radarr returns it after a copy: its own wiki link, its own labels.
RADARR_CF_AFTER_COPY = {
    **SONARR_CF,
    "id": 7,
    "specifications": [
        {
            **SONARR_CF["specifications"][0],
            "id": 3,
            "implementationName": "Release Title",
            "infoLink": "https://wiki.servarr.com/radarr/settings#custom-formats-2",
            "fields": [
                {
                    **SONARR_CF["specifications"][0]["fields"][0],
                    "label": "Regular Expression",
                    "helpText": "Custom Format RegEx is Case Insensitive",
                }
            ],
        }
    ],
}

SONARR_PROFILE = {"id": 1, "name": "HD-1080p", "upgradeAllowed": True, "cutoff": 3, "items": []}


@pytest.fixture
def stack(admin_client):
    """Sonarr + Radarr + Prowlarr rows in the DB, with keys."""
    with Session(get_engine()) as session:
        for name, kind, url in [
            ("Sonarr", "sonarr", SONARR_URL),
            ("Radarr", "radarr", RADARR_URL),
            ("Prowlarr", "prowlarr", "http://prowlarr.test:9696"),
        ]:
            service = Service(name=name, service_type=kind, url=url)
            store_api_key(service, "key")
            session.add(service)
        session.commit()
        yield session


def _ids(session: Session) -> dict[str, int]:
    from sqlmodel import select

    return {s.name: s.id or 0 for s in session.exec(select(Service)).all()}


# ------------------------------------------------------------- portability rules


def test_quality_profiles_are_declared_same_media_kind_only():
    assert config_sync.PORTABILITY["quality_profile"] is Portability.SAME_MEDIA_KIND
    assert config_sync.PORTABILITY["naming"] is Portability.SAME_MEDIA_KIND


def test_custom_formats_and_clients_are_portable_anywhere():
    for resource in ("custom_format", "download_client", "root_folder"):
        assert config_sync.PORTABILITY[resource] is Portability.ANY, resource


def test_series_profile_is_incompatible_with_a_movie_service(stack):
    """The test that matters — this is what stops a corrupt profile being written."""
    sonarr = Service(name="S", service_type="sonarr", url=SONARR_URL)
    radarr = Service(name="R", service_type="radarr", url=RADARR_URL)
    sonarr.id, radarr.id = 1, 2

    ok, reason = config_sync.compatibility(sonarr, radarr, "quality_profile")
    assert ok is False
    assert "different quality definitions" in (reason or "")

    # ...but a custom format travels fine between the same two services.
    ok, _ = config_sync.compatibility(sonarr, radarr, "custom_format")
    assert ok is True


def test_a_service_that_lacks_the_endpoint_is_incompatible():
    sonarr = Service(name="S", service_type="sonarr", url=SONARR_URL)
    prowlarr = Service(name="P", service_type="prowlarr", url="http://p:9696")
    sonarr.id, prowlarr.id = 1, 2

    ok, reason = config_sync.compatibility(sonarr, prowlarr, "custom_format")
    assert ok is False
    assert "no custom format" in (reason or "").lower()


def test_source_is_never_its_own_target():
    sonarr = Service(name="S", service_type="sonarr", url=SONARR_URL)
    sonarr.id = 1
    ok, reason = config_sync.compatibility(sonarr, sonarr, "custom_format")
    assert ok is False
    assert "source" in (reason or "").lower()


# -------------------------------------------------------------------- diffing


def test_cosmetic_metadata_is_ignored_when_comparing():
    """Regression from a live round trip.

    A custom format copied to Radarr comes back with Radarr's own `infoLink` and field
    labels. Comparing those made a correctly-synced format read as permanently
    out-of-date, so every item showed a false "update available".
    """
    left = config_sync._comparable(SONARR_CF, "custom_format")
    right = config_sync._comparable(RADARR_CF_AFTER_COPY, "custom_format")
    assert left == right

    spec = left["specifications"][0]
    assert "infoLink" not in spec
    assert "implementationName" not in spec
    assert "id" not in spec
    # ...but the behaviour is intact.
    assert spec["implementation"] == "ReleaseTitleSpecification"
    assert spec["fields"][0]["value"] == "\\b(AD|DVS|VO)\\b"


def test_a_real_difference_still_shows():
    changed = {**SONARR_CF, "includeCustomFormatWhenRenaming": True}
    diffs = config_sync._diff(SONARR_CF, changed, "custom_format")
    assert [d.field for d in diffs] == ["includeCustomFormatWhenRenaming"]
    assert diffs[0].current is False
    assert diffs[0].proposed is True


def test_naming_comparison_keeps_only_the_shared_fields():
    """Sonarr and Radarr naming barely overlap; copying per-type formats is meaningless."""
    sonarr_naming = {
        "id": 1,
        "renameEpisodes": True,
        "standardEpisodeFormat": "{Series Title}",
        "seasonFolderFormat": "Season {season}",
        "colonReplacementFormat": "delete",
        "replaceIllegalCharacters": True,
    }
    comparable = config_sync._comparable(sonarr_naming, "naming")
    assert set(comparable) == {"colonReplacementFormat", "replaceIllegalCharacters"}


# -------------------------------------------------------------------- preview


@respx.mock
async def test_preview_marks_create_update_identical_and_incompatible(stack):
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[SONARR_CF])
    )
    # Radarr already has it, byte-identical apart from cosmetics.
    respx.get(f"{RADARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[RADARR_CF_AFTER_COPY])
    )

    preview = await config_sync.preview(
        stack, resource="custom_format", source_service_id=ids["Sonarr"], item_id=1
    )
    by_name = {t.service_name: t for t in preview.targets}

    assert by_name["Sonarr"].action is Action.INCOMPATIBLE  # it's the source
    assert by_name["Radarr"].action is Action.IDENTICAL
    assert by_name["Prowlarr"].action is Action.INCOMPATIBLE


@respx.mock
async def test_preview_reports_create_when_the_target_lacks_it(stack):
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[SONARR_CF])
    )
    respx.get(f"{RADARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[])
    )
    preview = await config_sync.preview(
        stack, resource="custom_format", source_service_id=ids["Sonarr"], item_id=1
    )
    radarr = next(t for t in preview.targets if t.service_name == "Radarr")
    assert radarr.action is Action.CREATE
    assert radarr.target_item_id is None


@respx.mock
async def test_preview_writes_nothing(stack):
    """The whole point of a preview. A stray write here would be silent."""
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[SONARR_CF])
    )
    respx.get(f"{RADARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[])
    )
    post = respx.post(f"{RADARR_URL}/api/v3/customformat")
    put = respx.put(url__startswith=f"{RADARR_URL}/api/v3/customformat")

    await config_sync.preview(
        stack, resource="custom_format", source_service_id=ids["Sonarr"], item_id=1
    )
    assert post.call_count == 0
    assert put.call_count == 0


@respx.mock
async def test_preview_survives_one_unreachable_target(stack):
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[SONARR_CF])
    )
    respx.get(f"{RADARR_URL}/api/v3/customformat").mock(
        side_effect=httpx.ConnectError("refused")
    )
    preview = await config_sync.preview(
        stack, resource="custom_format", source_service_id=ids["Sonarr"], item_id=1
    )
    radarr = next(t for t in preview.targets if t.service_name == "Radarr")
    assert radarr.action is Action.ERROR
    assert radarr.reason


# ---------------------------------------------------------------------- apply


@respx.mock
async def test_apply_creates_on_the_target_and_strips_the_source_id(stack):
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[SONARR_CF])
    )
    respx.get(f"{RADARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[])
    )
    post = respx.post(f"{RADARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(201, json=RADARR_CF_AFTER_COPY)
    )

    results = await config_sync.apply(
        stack,
        resource="custom_format",
        source_service_id=ids["Sonarr"],
        item_id=1,
        target_service_ids=[ids["Radarr"]],
    )
    assert results[0].ok is True
    assert results[0].action is Action.CREATE

    import json as _json

    sent = _json.loads(post.calls[0].request.content)
    # Sending the source's id would collide with an unrelated record on the target.
    assert "id" not in sent
    assert sent["name"] == "novoiceover"


@respx.mock
async def test_apply_refuses_an_incompatible_target(stack):
    """Even asked directly, a series profile must not be written to a movie service."""
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/qualityprofile").mock(
        return_value=httpx.Response(200, json=[SONARR_PROFILE])
    )
    post = respx.post(f"{RADARR_URL}/api/v3/qualityprofile")

    results = await config_sync.apply(
        stack,
        resource="quality_profile",
        source_service_id=ids["Sonarr"],
        item_id=1,
        target_service_ids=[ids["Radarr"]],
    )
    assert results[0].ok is False
    assert results[0].action is Action.INCOMPATIBLE
    assert post.call_count == 0, "an incompatible profile was written anyway"


@respx.mock
async def test_apply_skips_targets_that_already_match(stack):
    ids = _ids(stack)
    respx.get(f"{SONARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[SONARR_CF])
    )
    respx.get(f"{RADARR_URL}/api/v3/customformat").mock(
        return_value=httpx.Response(200, json=[RADARR_CF_AFTER_COPY])
    )
    put = respx.put(url__startswith=f"{RADARR_URL}/api/v3/customformat")

    results = await config_sync.apply(
        stack,
        resource="custom_format",
        source_service_id=ids["Sonarr"],
        item_id=1,
        target_service_ids=[ids["Radarr"]],
    )
    assert results[0].action is Action.IDENTICAL
    assert results[0].ok is True
    assert put.call_count == 0, "an identical item was rewritten for no reason"


# ------------------------------------------------------------- settings store


def test_settings_round_trip_and_coerce(admin_client):
    with Session(get_engine()) as session:
        settings_store.write(session, "session_hours", "24")  # string from a form
        settings_store.write(session, "discovery_hosts", "10.0.0.1, nas.local")
        session.commit()
        stored = settings_store.read_all(session)

    assert stored["session_hours"] == 24
    assert stored["discovery_hosts"] == ["10.0.0.1", "nas.local"]


def test_settings_reject_out_of_range_values(admin_client):
    with Session(get_engine()) as session:
        with pytest.raises(ValueError, match="at least"):
            settings_store.write(session, "session_hours", 0)


def test_settings_reject_unknown_keys(admin_client):
    with Session(get_engine()) as session:
        with pytest.raises(ValueError, match="not an editable setting"):
            settings_store.write(session, "secret_key", "hunter2")


def test_secrets_are_not_editable():
    """The settings surface must have nothing sensitive on it."""
    for forbidden in ("secret_key", "jwt_secret", "data_dir"):
        assert forbidden not in settings_store.EDITABLE


def test_env_beats_the_database_and_reports_why(admin_client, monkeypatch):
    monkeypatch.setenv("MASTARR_SESSION_HOURS", "3")
    from mastarr.config import get_settings, set_db_overrides

    with Session(get_engine()) as session:
        settings_store.write(session, "session_hours", 99)
        session.commit()
        set_db_overrides(settings_store.read_all(session))
        get_settings.cache_clear()

        assert get_settings().session_hours == 3, "database wrongly overrode the env"
        assert settings_store.source_of("session_hours") == "env"
        described = {d["key"]: d for d in settings_store.describe(session)}
        assert described["session_hours"]["locked"] is True


def test_api_refuses_to_edit_an_env_controlled_setting(admin_client, monkeypatch):
    """Accepting the write and then ignoring it would be maddening to debug."""
    monkeypatch.setenv("MASTARR_LOG_LEVEL", "DEBUG")
    response = admin_client.put(
        "/api/settings", json={"key": "log_level", "value": "ERROR"}
    )
    assert response.status_code == 409
    assert "precedence" in response.json()["detail"]


def test_settings_endpoint_lists_provenance(admin_client):
    rows = {r["key"]: r for r in admin_client.get("/api/settings").json()}
    assert set(rows) == set(settings_store.EDITABLE)
    assert rows["session_hours"]["source"] in ("default", "database", "env", "file")
    assert "value" in rows["session_hours"]
