"""Service adapters. Every *arr interaction in Mastarr goes through this package."""

from .base import ArrAdapter
from .errors import (
    AdapterError,
    ServiceError,
    ServiceUnauthorized,
    ServiceUnreachable,
    UnsupportedOperation,
)
from .jellyseerr import JellyseerrAdapter
from .lidarr import LidarrAdapter
from .prowlarr import ProwlarrAdapter
from .radarr import RadarrAdapter
from .readarr import ReadarrAdapter
from .registry import (
    ADAPTERS,
    UnknownServiceType,
    build_adapter,
    default_ports,
    describe_types,
    get_adapter_class,
    known_types,
    type_for_app_name,
)
from .schemas import (
    BlocklistItem,
    CalendarEntry,
    DateKind,
    DiscoverPage,
    DiscoverResult,
    DiskSpace,
    DownloadClient,
    HealthIssue,
    HealthSeverity,
    Episode,
    HistoryItem,
    ImportCandidate,
    Indexer,
    LibraryDetail,
    LibraryItem,
    MediaRequest,
    QualityProfile,
    QueueItem,
    Release,
    RootFolder,
    Season,
    SearchResult,
    ServiceSnapshot,
    ServiceStatus,
    SystemStatus,
)
from .sonarr import SonarrAdapter
from .suggestarr import SuggestArrAdapter

__all__ = [
    "ADAPTERS",
    "BlocklistItem",
    "ImportCandidate",
    "Release",
    "CalendarEntry",
    "DateKind",
    "DiscoverPage",
    "DiscoverResult",
    "Episode",
    "JellyseerrAdapter",
    "LibraryDetail",
    "LibraryItem",
    "LidarrAdapter",
    "MediaRequest",
    "ReadarrAdapter",
    "Season",
    "AdapterError",
    "ArrAdapter",
    "DiskSpace",
    "DownloadClient",
    "HealthIssue",
    "HealthSeverity",
    "HistoryItem",
    "Indexer",
    "ProwlarrAdapter",
    "QualityProfile",
    "QueueItem",
    "RadarrAdapter",
    "RootFolder",
    "SearchResult",
    "ServiceError",
    "ServiceSnapshot",
    "ServiceStatus",
    "ServiceUnauthorized",
    "ServiceUnreachable",
    "SonarrAdapter",
    "SuggestArrAdapter",
    "SystemStatus",
    "UnknownServiceType",
    "UnsupportedOperation",
    "build_adapter",
    "default_ports",
    "describe_types",
    "get_adapter_class",
    "known_types",
    "type_for_app_name",
]
